stages:
  - build

build_executable:
  stage: build
  image: python:3.8  # Use an appropriate Python Docker image
  script:
    - pip install -r requirements.txt  # Install dependencies
    - pyinstaller main.spec  # Adjust with your actual script name
    - mv dist/main ./nmapscanner  # Rename and move the executable for easier access
  artifacts:
    paths:
      - nmapscanner
    expire_in: 1 week  # Adjust this value as needed
